### ISSUE TITLE
Hopper Limit is not working when it is bigger or equals to 160

### ISSUE THREAD

**Issue by UnioDex** [rlf/uSkyBlock#1009]
**Version:**
[20:52:52 INFO]: Name: uSkyBlock
[20:52:52 INFO]: Version: 2.7.3-alpha22
[20:52:52 INFO]: Description: Ultimate SkyBlock v2.7.3-alpha22-9687ae-457
[20:52:52 INFO]: Language: tr (tr)
[20:52:52 INFO]:   State: d=160, r=80, i=22,390, p=26,825, n=false, awe=false
[20:52:52 INFO]: Server: CraftBukkit git-PaperSpigot-"4c7641d" (MC: 1.8.8)
[20:52:52 INFO]:   State: online=true, bungee=true
[20:52:52 INFO]: ------------------------------
[20:52:52 INFO]: Vault 1.5.6-b49 (ENABLED)
[20:52:52 INFO]: WorldEdit 6.1.3;7a097ca (ENABLED)
[20:52:52 INFO]: WorldGuard 6.1 (ENABLED)
[20:52:52 INFO]: Multiverse-Core 2.5-b717 (ENABLED)
[20:52:52 INFO]: Multiverse-NetherPortals 2.5-b710 (ENABLED)
[20:52:52 INFO]: ------------------------------

When i set hopper-limit 159 from config limit will work. But when i increase it to 160 or higher it is not working. I can use infinite hoppers.

There is no error log.

**Comment by UnioDex** [comment]
This bug only happens when you put hoppers with another method than BlockPlaceEvent. I mean it is not counts how much hoppers island has. It counts how much hopper you put. So this is starts a problem with older islands and WorldEdit islands. Also schematics with hoppers also will be a problem.

**Comment by BlackBeltPanda** [comment]
The current hopper limit has some caveats:
It only increments when hopper placement fires the BlockPlaceEvent
It only decrements when hopper removal fires the BlockbreakEvent
It only counts from when the feature is introduced

This means hoppers placed via other means (like WorldEdit) or broken via other means (TNT/Creepers/WorldEdit) won't count. It also means any hoppers placed prior to the feature being introduced won't count.

This does create some problems, namely the following scenarios:
1. Hopper limit is introduced after players have already placed hoppers. Players can now have more hoppers than the limit specifies. Players break their hoppers and are now in the negatives.
2. Player is at their hopper limit but their hoppers are destroyed via explosions, or another plugin cancels the BlockBreakEvent when they break the hopper. They now have less hoppers than the limit but can no longer place any more.

I have a much nicer hopper limit system on my server that I wrote a year or two ago. It scans the island for hoppers in a very efficient manner. If they already have more than the limit, it breaks extra hoppers, returns the items to the player that were in them, and prints a list of location to the player where the broken hoppers were at. Not sure if @rlf would want that system incorporated since it does use considerably more logic than the current one but I'm willing to share. =)

**Comment by UnioDex** [comment]
It is complex a little bit. I think no need to break hoppers just cancelling new hoppers will be enough.

This plugin works: https://dev.bukkit.org/projects/hopperlimit
But it is checking only radius. If @rlf can integrate it island by island this issue will be fixed.

**Comment by rlf** [comment]
Not actively developing atm, so someone else should do it.
If I remember correctly, the initial hopper-limit was implemented by someone else (I just accepted a pull-request). The other "limit" capabilities of uSkyBlock analyses the island at the moment of placement/add/spawning - so that shouldn't depend on an increment/decrement approach - but that is not the case for the hoppers.

Feel free to change stuff, and make a pull-request.
