### ISSUE TITLE
Challenges Reset Exploit

### ISSUE THREAD

**Issue by xGamingDudex** [rlf/uSkyBlock#104]
If you have a party and you leave the island and create your own, then rejoin the party, then the challenges are reset from the last time you were on the same party. Even though it is a cooldown on the reset you can still get 12 obsidian a day if the island level of the party island is above 100. Guess you could solve it by saving the challenge process in on the island instead of the player. So that if a player returns to an island then he also gets his challenge process back.

**Comment by rlf** [comment]
I've done some thinking on this one.
Would it be unfair to share the challenge with the whole island? I.e. not have per-player challenge-completions, but have it shared? That way, all the members would work on the same challenges, but, there wouldn't be as high a "bonus" for playing together (since ONLY the first completion would yield the high reward).

But, somehow, it seems more fair - esp. when compared to players soloing USB.
Also, it would to a higher degree mean that they were "working together" - instead of just "helping each other".

**Comment by woolwind** [comment]
I struggle with this one too.  I've run a couple of skyblock challenges (start from scratch, how far can you get in x days) in temporary worlds to not disturb players existing islands, and got complaints that teams had too great an advantage over solos. To me, skyblock is an individual game, but getting to level 1000 takes for-flipping-ever by yourself - I haven't done it yet. 

How's this sound:

The island owner is the manager and gets the 'skylord' win.  Perhaps all challenges completed by teammates on an island get credited to the island owner, not the person doing them. 

An island owner can take on junior players as team-mates - show them the ropes, get free labor from them, and then  send them out into the world to start their own islands with an inventory full of stuff to give them a headstart on their own islands as recompense.   

So, when the teammate leaves to start their own island, their challenges are cleared but they may take enough stuff with them to quickly get through the easy challenges.

**Comment by rlf** [comment]
Hmm, I sort of see where you are heading.
But not clearing the inventory sounds like opening even greater exploits.
What would hinder players from "paying" to get invited to an island, before they start their own - getting a HUGE head-start over others?

**Comment by woolwind** [comment]
do we clear inventory now?

**Comment by rlf** [comment]
Yes.

**Comment by BlackBeltPanda** [comment]
I personally like the idea of:
Challenges per-island
The option to allow a player to be a "member" of a permission-specified number of islands
The option to allow a player to be an "owner" of a permission-specified number of islands

This would allow a player to be invited to another player's island while still keeping their own island.
Things like challenges would be tracked in the island files instead of the player files.
Should probably not allow an island member to invite the island owner to their island, otherwise they could share two islands and do the challenges twice.

**Comment by rlf** [comment]
What about inventories? Because, currently, we reset inventory, and delete island, when you accept an invite.

**Comment by dutchy1001** [comment]
Features are added to keep/clear inventories 

closing this for now as  there is no further input.
