### ISSUE TITLE
/c giving internal error

### ISSUE THREAD

**Issue by CottonBawl** [rlf/uSkyBlock#1104]
_Please paste the output from `/usb version` below_
```/usb version gives nothing
paste it here please (replace this text)
```https://pastebin.com/wdQtYpJL

_What steps will reproduce the problem?_
1.nothing
2.
3.

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin
https://pastebin.com/wdQtYpJL

(Not following the template will result in closing the issue.)

**Comment by Muspah** [comment]
This should be fixed in [the latest version from SpigotMC.org](https://www.spigotmc.org/resources/uskyblock-revived.66795/). Please open a new issue if the problem still persists in the latest version. You might need to remove your challenges.yml file in the plugins/uskyblock-directory and let the server regenerate it.
