### ISSUE TITLE
Challenges not working

### ISSUE THREAD

**Issue by Cyanoure** [rlf/uSkyBlock#1113]
Spigot: "git-Spigot-f6a273b-a639ae4 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)"
Vault 1.7.1-b91 (ENABLED)"
WorldEdit 7.0.0-beta-01;8975469 (ENABLED)
WorldGuard 7.0.0-beta01;01dfebe (ENABLED)
Multiverse-Core 2.5.0-b727 (ENABLED)

_What steps will reproduce the problem?_
1. I typed "/is"
2. I clicked on "Challenges"
(or type "/c")

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* some line server-log: [pastebin.com/TRShk73i](https://pastebin.com/TRShk73i)

(Thank you the template. :D)
(Sorry if I have bad english.)

**Comment by Lurkrul** [comment]
Update to the latest version: https://github.com/rlf/uSkyBlock/releases

**Comment by Muspah** [comment]
This should be fixed in [the latest version from SpigotMC.org](https://www.spigotmc.org/resources/uskyblock-revived.66795/). Please open a new issue if the problem still persists in the latest version. You might need to remove your challenges.yml file in the plugins/uskyblock-directory and let the server regenerate it.
