### ISSUE TITLE
uSkyBlock can't build against the latest WE 7 release

### ISSUE THREAD

**Issue by Muspah** [rlf/uSkyBlock#1117]
WorldEdit 7 (399e0ad) refactored the (Block)Vector classes and moved them all to a new math package. The latest uSkyBlock version (3667485) can't build against the latest WE7 release.

PR'ing a change fixing this in a few moments.

**Comment by Muspah** [comment]
Quick side-question regarding PR's, is @rlf or anyone else with write access still "alive" or is it just wasted effort trying to PR my changes and fixes? @SgtLegoTown maybe? (hi George, long time no see!)

**Comment by Muspah** [comment]
Compiled jar for everyone waiting: https://oss.pellegrom.pt/snapshots/uSkyBlock/uSkyBlock-20181106-1-a1f3317.jar

**Comment by BlackBeltPanda** [comment]
Hey, haven't seen @rlf in a while. Went ahead and merged the PR (hope he doesn't mind, lol) but that's about all I can do from my end.

I believe everyone who was working on USB has pretty much moved on due to study, jobs, or loss of interest in MC. In my case, I've been busy with work and haven't had time to keep everything going.

**Comment by Muspah** [comment]
Ah super, someone with write access, tnx! Didn't expect to see anything happening here :)
