### ISSUE TITLE
Challenges fix

### ISSUE THREAD

**Issue by SpectreDonut** [rlf/uSkyBlock#1164]
```
2.7.6-RC3
```

_What steps will reproduce the problem?_
1.Doing /c doesn't work

I know tons of people have posted this before. I have the latest update, and I don't know how to go into the source code. If there is an easier way of fixing the challenges, please tell me.

**Comment by Muspah** [comment]
Can you try using the latest uSkyBlock-build including the latest changes from this repository: https://oss.pellegrom.pt/snapshots/uSkyBlock/uSkyBlock-20190328-1-ec2a672.jar

Since the last maintainer of the plugin vanished, we're unable to push updates to the SpigotMC website :(

**Comment by Muspah** [comment]
This should be fixed in [the latest version from SpigotMC.org](https://www.spigotmc.org/resources/uskyblock-revived.66795/). Please open a new issue if the problem still persists in the latest version. You might need to remove your challenges.yml file in the plugins/uskyblock-directory and let the server regenerate it.
