### ISSUE TITLE
Incomplete build guide on github wiki

### ISSUE THREAD

**Issue by TadaCZE** [rlf/uSkyBlock#1261]
### Can't follow template - not related to the plugin itself
The problem is that the build guide at [https://github.com/rlf/uSkyBlock/wiki/Building](https://github.com/rlf/uSkyBlock/wiki/Building) is incomplete - the step sections are empty.

I, as a server owner, wanted to use an important feature, that was still in development, but there was no easy way to figure out how to build it, please fix!

Thanks :)

**Comment by Muspah** [comment]
Hi,

The wiki is outdated, but to be honest, it's not my first priority at the moment. Only one Maven-command is needed, which can be extracted from the Travis yaml if needed:

- mvn -nsu -Pi18n,1.15 clean install

If you do run profile i18n, you need to have gettext installed. Building without i18n should work too.

Otherwise, if you just want a snapshot build, you're able to grab the latest build from the repository:

https://www.uskyblock.ovh/downloads/master/uSkyBlock/
