### ISSUE TITLE
uSkyBlock Users dont have Perms to build after restart

### ISSUE THREAD

**Issue by Disorbs** [rlf/uSkyBlock#152]
So when i create a island and restart the server or invite someone and restart the server 
sometimes the island owner doesn't have perms or the island members dont have perms 
to build open chest ect even tho they are apart of the island and we are using the WG
protection to True, i need help with this as its the only problem thanks!

**Comment by Disorbs** [comment]
idk if i can get support for this is this is uSkyblock 2.0.0 but thought id ask because idk what to do :(

**Comment by rlf** [comment]
Sorry m8, that version is way too old. No clue what is going wrong there, but you have a better change posting on the forums (Dutchy might be able to help you).

**Comment by dutchy1001** [comment]
The issue here is that it is not saving the files on stopping the server. Are you using the "stop" command in console or just closing it by closing the window? (If your on a host you have no option then to stop the server with a "stop" command.)

When you close the server are your players still online? The files for usb are saved when players leave the server, closing this before it can save the files will loose their progress (but necessarily).
Can you post the server log (through pastebin) when starting and closing the server and inbetween have some players make an island and/or restart an island.
I cant promise if i can find the issue as what rlf said this is getting old and I'm concentrating aswell on the updated versions.
