### ISSUE TITLE
Some permissions doesn't seem to work

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [rlf/uSkyBlock#229]
My players have:
```
usb.biome.*
usb.lock
usb.island.*
```
But they can't change biome, lock the island, or set a warp.

**Comment by dutchy1001** [comment]
After been on your server trying out the perms, My island locks and unlocks normal, unfortunattely when I asked if someone wanted to enter my island none of the players reacted.

The biome change indeed didnt work, this looks like a permission issue using the *. I know from experiance that PEX doesn't like the wildcard in some cases. Try adding the biome names (E.G. usb.biome.hell or usb.biome.forest) instead of using the *. All biome names can be found on the bukkitdev and github wiki pages.

usb.island.* works normaly or we wouldnt be able to create or restart.

**Comment by TheOnlyRealTGS** [comment]
Yeah, could it be because I'm op?

**Comment by dutchy1001** [comment]
as OP you should have all the perms on default
