### ISSUE TITLE
Problem with UUID/Name changes

### ISSUE THREAD

**Issue by Lme999** [rlf/uSkyBlock#231]
Mojang introduced the possibility to change usernames today. When people change there username on my server I've been having to manually change leadership of the islands to the new name.

The bug? Is: For example let's say I were to change my username to "Lme9999", it would not recognize the change and it would force me to create a new island, I would not be able to access my old one at all unless an admin transferred leadership to me. Can an update be put out to fix this?

**Comment by dutchy1001** [comment]
We are aware of the problem and trying to work it out how to go about it. For the mean time adding a player as owner to their island through a WorldGuard command is the easy fix for now.
The command is:
/region addowner XXX,YYYYisland [name] (I think this is case sensitive)
Obvious you need to have access to the island.yml to see the right co-ords

**Comment by BlackBeltPanda** [comment]
"/dev goto <newname>" should still work for going straight to their island and getting the region name. =)

**Comment by Lme999** [comment]
I would rather not have to change the regions every time a player changes his/her username..

**Comment by dutchy1001** [comment]
Yhe islands are changed on loggin in when players have changed their name, it's just not updating the WG regions. 
As soon we have a fix we will release this so it will all go automatic without having to change anything by the serverowner or an admin.

**Comment by TheOnlyRealTGS** [comment]
I saw this error: http://pastebin.com/3268Rxgr

**Comment by BlackBeltPanda** [comment]
I also get that error when teleporting to a player's island after they've changed their username.

**Comment by dutchy1001** [comment]
After some investigation it appears that there is a setting in WorldGuard to convert all regions at once. 
You can find this setting in the "plugins/woldguard/config.yml".

[CODE]
regions:
    use-scheduler: true
    uuid-migration:
        perform-on-next-start: false
        keep-names-that-lack-uuids: true
    use-creature-spawn-event: true
[/CODE]

Change this "perform-on-next-start: false" to true.
This will add all the UUID to the "owners" tag in the region file. If you have a big player DB that playes USB then this can take some time. This is unfortunattely out of our hands as this is a WorldGuard issue.

**Comment by BlackBeltPanda** [comment]
Awesome, didn't know about that config option. =D

**Comment by dutchy1001** [comment]
neither did i till i looked for something else lol

**Comment by TheOnlyRealTGS** [comment]
Thanks, I'll try that!

**Comment by TheOnlyRealTGS** [comment]
> After some investigation it appears that there is a setting in WorldGuard to convert all regions at once. 
You can find this setting in the "plugins/woldguard/config.yml".

So it turns out that you should have done this 3 days ago.
It can't find UUID for players who changed their name
.... Luckily I have a database for 61k player names before the name switch, and only 53 players had changed their name, so I added them manually.

Also, @dutchy1001 you guys should make a way to update the entry/exit message for players who changed their name. (Just grap the name from the leaders UUID and readd the messages?)

**Comment by dutchy1001** [comment]
@TheOnlyRealTGS 
we are aware of the update to the greeting/farewell message isnt working and has already been talked about. 
As there are some more issue's due to the UUID we need to sort them all out at once.
Our dev has a normal job too so it's not always possible to get a fix out asap. 

We are aware and as soon we can we will have an update.

**Comment by TheOnlyRealTGS** [comment]
Sounds good!

**Comment by rlf** [comment]
Should be fixed in v2.2-HF7

**Comment by dutchy1001** [comment]
An explanation of this can be found in issue  #241, read my post [here](https://github.com/rlf/uSkyBlock/issues/241#issuecomment-73593753)

This can be closed now
