### ISSUE TITLE
Updating from 1.0.8

### ISSUE THREAD

**Issue by Pixiio** [rlf/uSkyBlock#232]
I'm trying to update from 1.0.8 to the new uSkyblock. I've tryed multiple things:
* Update to 2.0.0 uSkyblock first. (Talabreks uSkyBlock)
* Update to your version directly v2.2-HF4

More information about my structure:
* There's information saved at orphanedIslands.bin.
* All players are saved in the map ''players''. Screenshot: http://i.imgur.com/Hvoaeud.png

What goes wrong?
* With version 2.0.0 none of the old Skyblock's are recognised.
* With your version it looks like it's disabling itself, the error: ''is it up to date?''

Notice:
I've found a weird thing: i see there are 8 yml files in the map ''Players''. It look's like only my player file is updating ther, all the other one's are inactive players: http://i.imgur.com/sy25yXZ.png. Example of a file: http://pastebin.com/RXTvwTV3

Version:
* Version 1.8 Spigot
* Worldguard + WE 6.0 (1.8 version)
* Vault 1.5
* uSkyblock versions are noted above.

Please help.
Thanks alot.

**Comment by dutchy1001** [comment]
all players saved in the "players", are they all .yml files? If not that could be your problem. You sure it's a orginal usb 1.0.8 or could it be an altered version?

**Comment by Pixiio** [comment]
Hi Dutchy,

Thanks for your fast repley. No, only 8 of them are, one of them is mine. All the others don't have an extension as you can see in the screenshot in the other post above.

I'm pretty sure we are using 1.0.8 and not a modified version. But if you want to check this:
Plugin.yml http://pastebin.com/ZavpGi99
uSkyblock.jar http://www.filedropper.com/uskyblock

Thanks alot.

**Comment by dutchy1001** [comment]
I think your using a normal version of 1.0.8. 
All the files that dont have an .yml extention are those players that haven't been online since updating to v2.0.0 beta(the orginal of Talabrek)?

If those screen shots are all your players why dont you start with a fresh world as there arent many?
That way you save a lot of hassle.

Incase you want only to update check the config as from 1.0.8 to v2/v2.2 the value's have changed, e.g. height, spawnsize, etc etc
Also from v1.0.8 to v2/2.2 challenges have different discriptions due to adding a GUI (this can give errors as there isnt enough characters on the GUI compare to the chat it was before), lastIslandconfig has been changed from the main config to it's own config.

Basicly before opening the server again make sure you check the configs to alter the value's used in v1.0.8 or you will get trouble of overwriting islands. 

Unfortunattely we can do anything about that fact that value's have been changed between v1.0.8 and v2.0.0, this was done before we took over.

**Comment by Pixiio** [comment]
Hi Dutchy,

No, we have 80.000 player files and only 8 of them are .yml files.
In wich version did the files change to .yml files?

Thanks alot.

**Comment by dutchy1001** [comment]
I think, but not 100% sure, that in v1.0.8 the files changed to .yml

**Comment by rlf** [comment]
Odds are, that you will be able to use `/usb import wolfwork` to get the rest converted to yml files.
But do make a backup first.

**Comment by Pixiio** [comment]
I'm going to try this monday night, will post the results.

Thanks!

**Comment by i9hdkill** [comment]
The importer seems to work but region saving is not working correctly. Maybe it's an World Guard limitation?
He is not able to rename the world guard temp region file.
Here is the error.
http://pastebin.com/8YcfVGqn
Someone else having the same issue?

Maybe it's working when the convert process saves regions in batches and not 1 by 1?

At least I think it needs a fix on your side.
Would appreciate it.

Trying to convert from 1.0.8 to 2.2.

WorldGuard Build 1567

**Comment by rlf** [comment]
Yes, sounds sensible - we are looking into the WG support - and this will be fixed - it can be ignored for now.

**Comment by i9hdkill** [comment]
great thx, looking forward to finally switch over to 2.X due to the Name Changes

**Comment by rlf** [comment]
Since the original issue seems to be resolved - closing this for now (the WG is a separate issue, fixed in the upcoming release).
