### ISSUE TITLE
Block bedblock exploit of Bedrock Removal

### ISSUE THREAD

**Issue by CassandraWipf** [rlf/uSkyBlock#240]
Players can place a bed on grass (Grown with bonemeal) in front of a block, and the top of the bed will delete the block it is taking over. This can be done to the Bedrock on the island, breaking the island. Since this is a Minecraft bug, is there a way you can modify it so a bed cannot be placed within one block of the bedrock?

Version 2.2-HF7

**Comment by rlf** [comment]
It can be done - but not sure we want to further impact performance in this way - will get back to you

**Comment by rlf** [comment]
I haven't been able to locate the "minecraft bug" you are referring to. Could you please provide some info?
Additionally, how is it breaking the island, that there is no bedrock on it?
The bedrock is only used in the `/usb island register` command.

**Comment by DogsPaw** [comment]
Which we were having to run due to name changes. It was kinda working. Worked for some players. Didn't work for others. We thought the Bedrock had more of an impact on Skyblock. Hopefully we will see what happens in HF8.

This post is also for my Server, we found a video for 2013-2014 of a player demonstrating how this works. Place grass on a grass block near Bedrock. Place a bed on it (Takes a few tries but doable) it will replace the grass, while the head of the bed deletes whatever block is in its way.

**Comment by CassandraWipf** [comment]
Here is a video of a player doing it on the server https://www.youtube.com/watch?v=MRPhYGt4T94

**Comment by rlf** [comment]
Ok, ty.
Is this a real problem?
I mean , for us to avoid this - we need to have some code execute on every block-placement - and since it is in effect trying to "fix a bug in Minecraft", it isn't really doing anything constructive.

The only time we use the bedrock (after island creation), is when an admin wants to re-assign the island.

If a player has used this exploit to delete the bedrock - so be it - their choice - their loss.

**Comment by dutchy1001** [comment]
this is a glitch in minecraft and not for us to fix. Most server owners do have a rule not to abuse glitches when found out.
This is upto the server owner to take action if players removing the bedrock.
