### ISSUE TITLE
Level calculation of island can be improved

### ISSUE THREAD

**Issue by Seadragon91** [rlf/uSkyBlock#247]
It exists a interface named [ChunkSnapshot](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/ChunkSnapshot.java). With that you could get the copy of the chunk and do the calculation in an asnyc task.

I use this in my skyblock plugin, the calculation is very quick and don't freezes the main thread.

**Comment by rlf** [comment]
Sounds like a good suggestion.

**Comment by woolwind** [comment]
how does it work if two neighboring islands share some chunks?

**Comment by Seadragon91** [comment]
Well you have the chunk coords, the island distance and then you can calculate the min and max positions of the island. Nothing difficult here.

**Comment by rlf** [comment]
Well, the difficulty that comes to mind is, iterating over all the active islands (N), for each n in N, find the border-regions and the inner-chunks (XZb, and XZi) (synchronously), for each xz in [XZb, XZi] make a snapshot of that chunk (synchronously), and pass it on to an async task that calculates the score.
Once the calculation is done - inform the user (synchronously), and update the top 10.

I think the performance improvement is worth the effort.
But it's definitely not "easy-peasy", since we need to chain a lot of "sync" commands to "async" commands, and still have everything perform, and not fail or leak memory.

**Comment by Seadragon91** [comment]
Well okay. In my plugin I only update the island level, when the player occurs the command. This also updates then the informations passed to dynmap.

**Comment by rlf** [comment]
Yes, and I agree, this is definitely the way to go (moving forward) - I have begun preparing the code - but as I stated above, we also have some "periodic-updating of the top ten", which has some more complex issues with the swapping between sync and async processing.
Still doable though - just need to find the best way to do it, without taking up too many resources (both CPU and memory wise).

**Comment by rlf** [comment]
Introduced in v2.3-HF3 - but only for manual calculation (i.e. `/is info`), not for the periodic update of top-10.

**Comment by dutchy1001** [comment]
working nice now with new pages

**Comment by Seadragon91** [comment]
I will not test it, I opened this because I use ChunkSnapshot in my skyblock plugin and it's a very good improvement for island calculation.
Well done @rlf, good job!

**Comment by rlf** [comment]
Thanks for the help @Seadragon91 ! Much appreciated. Closing it for now (even though we still need to optimize the periodic calculation).
