### ISSUE TITLE
Command list shown on every command without permission

### ISSUE THREAD

**Issue by EvilOlaf** [rlf/uSkyBlock#293]
If a player executes a command and does not have the proper permission for it he well always be show the index of all available commands.
I think this is not pretty handy and a message that tells the player that he has no permission to do so would more useful.

If a player has no permissions to use USB at all he should not even be able to open the island menu and instead get as already suggested a hint about his lack of permission.

If this has been already asked/criticized I am sorry, could not find the related issue.

**Comment by rlf** [comment]
We do this on purpose, since players aren't even allowed to see the command they don't have permission to.

I.e. if he do `/is help` only commands he has access to is listed.
That means, invoking a command without permission, is treated the same way as invoking an invalid-command.

I do understand what you are saying though - and I think you are right.

**Comment by rlf** [comment]
v2.2-HF13c

**Comment by EvilOlaf** [comment]
So tested it.
After the "You do not have access" message is the needed permission node visible for all players which should be for op only.

**Comment by rlf** [comment]
Hmm, true... perhaps... no harm in showing it to all, is there?

**Comment by EvilOlaf** [comment]
Harm actually not, no. Could just be confusing for players without server management knowledge so I think this feature somewhere has its right to exist.

**Comment by dutchy1001** [comment]
only Op showing permission nodes players just getting help file/command help

fixed
