### ISSUE TITLE
Problem with lava

### ISSUE THREAD

**Issue by JG6521** [rlf/uSkyBlock#307]
hope this is the right place to post this but can anyone help with my issues please, thanks. :)

is anyone else having a problem with lava not killing animals/mobs & flame not working on a bow even though fire aspect works? & a challenge you have to stand within 10 blocks of 15,000 torches on skyblock.

don't know if these have been/are getting sorted but thought I would point them out, thank you & keep up the grate work :D

**Comment by rlf** [comment]
a) The lava is configurable - But shouldn't influence mobs - the forums tell you are not alone - not sure what is causing it though.

b) The torchbearer challenge has been "fixed", and will be fixed in the next release, until then, just add `radius: 52` to the challenge in `challenges.yml`.

See here https://github.com/rlf/uSkyBlock/blob/master/src/main/resources/challenges.yml#L600

**Comment by rlf** [comment]
Reg. the flame issue, it might be a world-guard flag being wrong.
Could you please include the info requested here: http://dev.bukkit.org/bukkit-plugins/uskyblock/

**Comment by rlf** [comment]
No answer from reporter - closing
