### ISSUE TITLE
Translate messages

### ISSUE THREAD

**Issue by xwest** [rlf/uSkyBlock#441]
I can translate messages to spanish
Only need lang file. (:

Skype: xwestmc

**Comment by dutchy1001** [comment]
For the translation files go [here](http://dev.bukkit.org/bukkit-plugins/uskyblock/pages/localization/).

Files will be added on next (pre) release. Do have in mind that the language system still has bugs. Due to other issue's we like to fix first the language system has to wait. Files made will still be added so there not made for nothing.

**Comment by dutchy1001** [comment]
Due to many bugs in the language system we will change this to something else.
Language issue's can be opend again when we add a new system,
