### ISSUE TITLE
Top ten generation failed

### ISSUE THREAD

**Issue by alexlab963** [rlf/uSkyBlock#454]
Hello,

As you can see in the title the topten generation is failed on loading.
In additipn it is a huge spams since it tries to create it 3 times every 10 seconds

My topten configuration:
    useTopTen: true
    topTenTimeout: 50
    autoRefreshScore: 0
    topTenShowMembers: false

There are no errors on startup

**Comment by dutchy1001** [comment]
This has been a bug a while ago in an older version. Please read [here](https://github.com/rlf/uSkyBlock/wiki#how-to-post-an-issue) and post that info.

**Comment by alexlab963** [comment]
server version (Craftbukkit/Spigot): 1.8.8 spigot
uSkyblock version: v2.3-HF3
WorldEdit version: 6.1
WorldGuard version: 6.0 beta
Vault: 1.5.6

**Comment by dutchy1001** [comment]
Can you post, through [pastebin](http://pastebin.com/) (it's free) the log were it spams (preverable a full log from start to spam).

"WorldGuard version: 6.0 beta" is questionable as there are a few beta's. Update to [6.1](http://dev.bukkit.org/bukkit-plugins/worldguard/files/46-world-guard-6-1/) or use a dev build from [here](http://builds.enginehub.org/job/worldguard?branch=master).

**Comment by alexlab963** [comment]
I updated to the latest worldguard 6.1.1 snapshot still no luck
Here is my pastebin log http://pastebin.com/gtYLscGj

**Comment by dutchy1001** [comment]
Is there only your island on the server or do you have more islands?
Try the command "/usb topten" to re-generate the top ten list and make sure your island has a level of 10+ (diamond block gives 5 levels per block). If I'm remebering right you need atleast level 10 before it shows in the topten list. 
It could also be that you need to do the command "/is info", when standing on your island, before the topten list will properly generate. This used to be a bug and I'm not sure if that was fixed in v2.3-HF3 or in later pre-releases.

Even that the spam is odd to me as I dont get this, with a clean skyworld or one with many islands it still shouldnt spam. If all doesnt help try the latest pre-release [here](https://github.com/rlf/uSkyBlock/releases/tag/v2.3-HF7j)

**Comment by alexlab963** [comment]
It looks like it works with the latest version :)
Thanks

**Comment by dutchy1001** [comment]
I have to warn you that the latest pre-release still has some bugs (reason it's not a public download).
One added feature is "trust" (/is trust [name] and /is untrust [name]), this allowes a player to trust someone to help on the island without being in the "party" but still be able to build and break.
