### ISSUE TITLE
Cosmetic Questions

### ISSUE THREAD

**Issue by Scraapy** [rlf/uSkyBlock#470]
The following is purely cosmetic and is not a huge problem.

When reseting my island I get the following messages:
![image](https://cloud.githubusercontent.com/assets/12485039/9972597/f2d1be9a-5e33-11e5-97a2-c0a4207d5104.png)
I've already created a thread about the /is restart one, and the 'The island you are on is being deleted' one is fine too, but is there anyway of getting rid of / modifying the '[skyblock] The island has been created', and the 'Player doesn't have an island or' messages? I find them a little bit annoying and ugly.

Also, is there any plans for a messages.yml? I'd really like configurable messages.

Oh yeah, I'm sorry for the mass of posts here, just trying to get everything polished.

**Comment by rlf** [comment]
It's pure awesomeness of colorfulness.

No, we won't have a messages.yml, because we use gettext for a full blown translation-support instead.
So, not on the roadmap, but we might consider adding it, but only for "overriding" messages locally.
I think the "Teleporting..." must be from some other plugin, the rest is us!
The [skyblock] message is part of the island-log, and could probably be hidden without losing any info, since it's broadcast to all members of the island, which in this case, is only you.

The "Player doesn't have an island or it's already protected" should not be part of the latest builds, but since you failed to provide the info we ask for in bug-reports, it's hard to say...

And finally, the "**" messages are WG messages for entry/exit of the region.

But just for you, I'll get rid of the [skyblock] message, and make it much more purdy!

**Comment by Scraapy** [comment]
Uh, I don't know what to add in bug-reports, and couldn't find a thread.
Here is my version information right from console:

20:09:54 INFO]: Name: uSkyBlock
[20:09:54 INFO]: Version: 2.4
[20:09:54 INFO]: Description: Ultimate SkyBlock v2.4-f9e9f6-dev
[20:09:54 INFO]: Language: en (en)
[20:09:54 INFO]: ------------------------------
[20:09:54 INFO]: Server: CraftBukkit git-Spigot-fdc1440-53fac9f (MC: 1.8.8)
[20:09:54 INFO]: ------------------------------
[20:09:54 INFO]: Name: Vault (ENABLED)
[20:09:54 INFO]: Version: 1.5.5-b47
[20:09:54 INFO]: ------------------------------
[20:09:54 INFO]: Name: WorldEdit (ENABLED)
[20:09:54 INFO]: Version: 6.1;no_git_id
[20:09:54 INFO]: ------------------------------
[20:09:54 INFO]: Name: WorldGuard (ENABLED)
[20:09:54 INFO]: Version: 6.1
[20:09:54 INFO]: ------------------------------

I'm pretty sure it's the latest build, unless you updated in the last few hours.

**Comment by rlf** [comment]
Is this better?
![image](https://cloud.githubusercontent.com/assets/503044/9973514/876a2b2e-5e74-11e5-8748-21d6d57294b5.png)

I just haven't seen that white thingy for a while, but it might be in the "latest official release", that is why we ask for the version info always.

I agree, esp. for island restarts, the console is a bit busy, but that is only because, a lot of the messages comes from "normal operation" (i.e. WG entry/exit, teleporting etc.)

**Comment by rlf** [comment]
We made your suggestion for custom messages into v2.4.1 - hope you enjoy it! :D
