### ISSUE TITLE
sendToSpawn is ignored

### ISSUE THREAD

**Issue by dutchy1001** [rlf/uSkyBlock#49]
When teleporting to the skyworld you spawn at X=0 Y=0 Z=0. This used to be Z=150, same level as the islands.

When jumping of the island and the setting "sendToSpawn" is set to false you should spawn in the skyworld not in the default "world".
When the setting "sendToSpawn" is set to true it should go to the default "server" spawn.

**Comment by dutchy1001** [comment]
sendToSpawn: false 
is spawning in the default world, not in the skyworld as it should so I cant test if it goes to location X=0 Z=150 Y=0

**Comment by rlf** [comment]
Not sure how this is intended to be used? Is it not competing with the MV-Core respawnWorld setting?

**Comment by dutchy1001** [comment]
It was intended to use as when it is set to true "essentialsSpawn" should take over the spawn and spawn the player in the world set by "Essentials"
For reference see http://wiki.mc-ess.net/wiki/Command_Reference and look at "Setspawn" and "Spawn"

Nothing been mentioned about MV-Core when using this setting.

**Comment by rlf** [comment]
Should be fixed in v2.2-HF1.
a) sendToSpawn is used when initially importing the world - to use MV to set the respawnWorld.
b) If sendToSpawn is false, we teleport players to "skyworld-spawn" when they respawn.
c) If sendToSpawn is false, we teleport players to "skyworld-spawn" when they leave/is kicked from at party.

**Comment by dutchy1001** [comment]
tested and fixed
