### ISSUE TITLE
Feature request: show holograms with neighbors

### ISSUE THREAD

**Issue by hunter688** [rlf/uSkyBlock#521]
Please add optional depedency to Holographic displays ( http://dev.bukkit.org/bukkit-plugins/holographic-displays/ )

Using api is possible add new feature - show neigbors of player's island.

Example code, which I write some months ago for old talabrek's uSkyBlock: http://pastebin.com/RH1Rk97T

Code isnt perfect, but works without problems on my server.

I think new feature will lead to greater competition (and fun) among players.

**Comment by csorrows** [comment]
My experience with using Holographic displays in a build-able area is that they get in the way. You can not build in the block at the center of it. Maybe putting them 1 block off the edge would work if this was implemented. Although, I do not think I would personally use it.

**Comment by Adam4CZ** [comment]
I thing it's a good idea, because players often want to know their neighbours.
It's true that they can interfere in building the island, because it's invisible armor stands, but you can turn off this holograms. On @hunter688's server you can switch holograms with command */is neighbours*, so you can switch off, if you don't need know the neighbours :-)

**Comment by csorrows** [comment]
Sounds like a good solution to the issue I presented. I see no other issues with it.

**Comment by rlf** [comment]
Take a look at Holographic-Scoreboard.
We won't integrate with any holograms directly, but we might add the option to see neighbors, if you want that.

**Comment by rlf** [comment]
I do not see this as something uSkyBlock needs, so this feature is hereby rejected.
