### ISSUE TITLE
cant generate new worlds correctly

### ISSUE THREAD

**Issue by woolwind** [rlf/uSkyBlock#545]
It's been a while since I set up a skyblock world from scratch so am probably failing somewhere. I have 2.5.3 and wanted to play with the nether. I have spigot  1.8.8, Multiverse-Core v2.5-b699.

I created a shiny fresh world with uskyblock, let it generate it's new config file. Shut it down, set island protection 96,  distance 128, and nether true.  set spigot.yml world generator for skyworld to uSkyBlock.

deleted the scratch world that had gotten created, restarted spigot.

Found myself standing in a landscape in a hole 2 blocks deep, on top of a bedrock set at y=64

I did /is create and in a short while I was standing on an island hovering over an ocean. there's a sea temple down there somewhere.  Nether looks like any other nether I've ever seen.

There are no startup errors from uSkyBlock, but I do have a mess of these in the logs:
[19:44:52] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to uSkyBlock v2.5.3
	at us.talabrek.ultimateskyblock.util.LocationUtil.findRoofBlock(LocationUtil.java:188) ~[?:?]

**Comment by csorrows** [comment]
The is no reason to modify or delete the plugin created world. I suggest delete the uSkyblock folder and uSkyblock world and start over.

After first run, shut it down and change you settings in the config. There is no reason to modify the auto generated world in any way.

**Comment by csorrows** [comment]
Also, the generator should automatically be set in multiverse, do not change it in the spigot.yml

**Comment by rlf** [comment]
The issue you are experiencing has been reported multiple times in the past.

It's always caused by the world not correctly getting uSkyBlock as generator.
This CAN happen, if your skyworld is your default world, or if uSkyBlock is not the one creating/configuring the world.

For a "clean install", I'd follow @csorrows suggestions, and do this:
a) Shutdown server.
b) Delete skyworld and skyworld_nether folders (the worlds, not the plugin)
c) Make sure uSkyBlock/config.yml is correctly configured.
d) Start server.

This way, uSkyBlock will create and configure the worlds, ensuring the generators get set correctly.

If this does not work, odds are your Multiverse-Core is not compatible with uSkyBlock - then please share your complete server-log (using pastebin) with us.

**Comment by dutchy1001** [comment]
To add to the above, If you want the skyworld to be the world the spawn in when they log on to the server there is something better you can do then changing the ```server.properties```.
With the use of Multiverse-Core you can set a default world to spawn in and leave the orginal default world "world" alone.
You only need to do 2 command:
/mv conf firstspawnoverride true  (This might already be set to true by default)
/mv conf firstspawnworld skyworld

After these to commands restart the server (not sure it's needed) and any new player should just spawn in the skyworld.

**Comment by csorrows** [comment]
Sorry if it seemed fragmented and I missed removing the skyworld_nether world. I was typing it out on my little phone.

**Comment by woolwind** [comment]
Yes, I'd tried to set up with 'skyworld' as the default world in server properties because having an unused world around seemed wasteful, but I guess it really needs to be there. Thanks guys.

the nether island is hilarious, this is going to make them nuts :D

**Comment by rlf** [comment]
Glad to hear - looking forward to ideas and other feedback from the players!

**Comment by woolwind** [comment]
I'm standing up an event world for over thanksgiving with holiday challenges and stuff and I'm thrilled to have the nether islands to add to the chaos. Drop by in a couple weeks and see it in action :)
