### ISSUE TITLE
Custom-commands on island-create

### ISSUE THREAD

**Issue by GiansCode** [rlf/uSkyBlock#546]
Hello.

Feature 1 (Commands (with delay) on Island Create):  Set commands to execute whenever a player creates his/her island. 

Example config:

onIslandCreate:
    commands:
    - '[delay=5] [console] cratekey give %player% Tier1 1'
    - '[delay=1] [player] me has just created an island'

Feature 2 (Naming items in a chest): I was wondering if it'd be possible to set the name, lore and enchantments for items that spawn in the chest on Island create? This would allow us to add unique item by fully replicating them from how they look in other plugins (IE: TokenEnchants Token Item).

**Comment by rlf** [comment]
Good suggestions.
Feature 1 I have been considering my self, since we already have it for challenges.
Also, it could be used to a lot of other stuff, i.e. resetting permission-nodes controlled by challenges, creating holograms etc.

Feature 2  - We considered this a while back, but it would sort of require us to re-implement the kit-code used by Essentials. IMO, feature 1 could make feature 2 obsolete, since you could simply give the player a kit using commands.

Note: NEVER post multiple issues as one - much better to have separate issues - so we can reject or promote them individually.

**Comment by GiansCode** [comment]
Alright! I'll start making them separate.

Yeah. If Feature 1 gets in, it's created infinite possibilities.

**Comment by rlf** [comment]
oups, wrong issue referenced in the above commit *blush*
