### ISSUE TITLE
When upgrading from 2.4.7 to 2.5.3 island-regions are resized by 1 block

### ISSUE THREAD

**Issue by i9hdkill** [rlf/uSkyBlock#552]
Hi

Plugins:

Description: Ultimate SkyBlock v2.5.3-a7db3e-376
Server: CraftBukkit git-Spigot-5f38d38-18fbb24 (MC: 1.8.8)
Name: Vault (N/A)
Version: 1.5.6-b49
Name: WorldEdit (N/A)
Version: 6.1.1-SNAPSHOT;3399-b19cd9be
Name: WorldGuard (N/A)
Version: 6.1.1-SNAPSHOT.1628-e28b236
Name: AsyncWorldEdit (N/A)
Version: 3.2.2

Using Mysql storage for worldguard regions.
I updated from 2.4.7 to 2.5.3
After updating, player islands regions got a resize from 100 to 99 blocks.
That means, on two sides of existing islands the worldguard island protections is missing for 1 block.

Image for clarification:
http://i.imgur.com/WI4cjTE.jpg

At first i thought it's my bad, but I did look into it and compared a mysql region backup from yesterday (2.4.7) with the recent mysql regions and found what I expected.
The region is 1 block short on two sides.

Copied example region from the mysql region dump:
Island coordinates:
http://pastebin.com/7ydSJspm

Protection before and after the update is untouched at 100 blocks.

Checked the new generated config and the config in /backups
Both are showing 100

I am afraid that newly generated islands could break the whole pattern...

Did a bit code digging, but I am not really into into it:
This or this could be the issue?!
https://github.com/rlf/uSkyBlock/blob/ede8a22dc5ea07e2c43f828cce4142bc599c09dd/uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/uSkyBlock.java#L1028
https://github.com/rlf/uSkyBlock/blob/89656bcfd9c9326200d894f4835e1a4f1743e04a/uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/island/IslandLogic.java#L199

**Comment by rlf** [comment]
That is on purpose.
It allows us to have regions be chunkaligned, and is required to enable the Nether island.

Why is it a major issue?

**Comment by i9hdkill** [comment]
Ehm. Players cannot access/build on this specific part on their island. Many people build walls and stuff like stuff like that and cannot edit them enymore because it's no longer part of their island.

**Comment by rlf** [comment]
If it's a major issue, I suggest rolling back to the 2.4.7 release.

We need the ability to align islands on chunks borders - for performance reasons, so we are not going to change that mechanic.

Previously all regions/islands where created around the center=(n*distance, islandHeight, m*distance) with corners (center-radius, 0, center-radius) to (center+radius, 255, center+radius).

Unfortunately, that formula would never allow us to align islands on chunk-borders, since a chunk is 16x16 blocks.

Now we use (center-radius) to (center+radius-1).

If you currently have distance > protectionRange, then you could increase protectionRange with 1 - and by that give them an area a bit larger than the previous one.

Offcourse, this will not be chunk-aligned, if the previous one was.

**Comment by Deathinflames** [comment]
I have a quick question on this, if the island region is manually resized to once again give the player access to those blocks that were placed in this space before it was resized do those blocks get calculated back into the island level?

If not, does the plugin use its own method instead of what is inside a world guard region to calculate the island level? Thank you

**Comment by rlf** [comment]
No and yes.

**Comment by dutchy1001** [comment]
no further input, closing for now
