### ISSUE TITLE
Lang FR

### ISSUE THREAD

**Issue by MrJuju0319** [rlf/uSkyBlock#589]
Bonjour,
La langue Français sur uskyblock actuel crée des bug sur le plugins (utilisation des coffre impossible, /is planté , ...).
Pouvez vous développer la langue fr sur le plugins ?

Hello, 
The French language on uskyblock current create bug on the plugins (use of the impossible chest, / is crashed) can you develop the language fr on the plugins?

Email : Xxjuju0319xX@gmail.com
Merci, Thanks You

**Comment by dutchy1001** [comment]
It is a known issue that language files can cause a bug. 
This should be fixed in [v2.5.5](https://github.com/rlf/uSkyBlock/releases/tag/v2.5.5) but not sure yet. As you didnt post the default info it is just a guess to update. See [here](https://github.com/rlf/uSkyBlock/wiki#how-to-post-an-issue) how to post an issue.
If you still have the issue after updating to v2.5.5 let me know.

To use the chest (wooden and/or enderchest) you need to use the plugin Chest Command GUI as explained [here](https://github.com/rlf/uSkyBlock/wiki/The-use-of-3rd-party-plugins), this also indicates you are using an older version.
