### ISSUE TITLE
High cpu usage after doing /is top and /is level

### ISSUE THREAD

**Issue by det483** [rlf/uSkyBlock#604]
Hello,

If a player uses the command /is level the cpu of the dedicated server goes up to a very high level, it can go to 250% cpu power of that skyblock process, without using the /is top command it's normal 20 - 60% cpu power of the skyblock process. 
Every time a player uses that command it looks like everything is calculated again, I changed some things in the configuration but I doesn't seem to work.

This is the configuration of the is top and is level part; http://pastebin.com/WX41BD27

Output of /usb version; http://prntscr.com/9j81xe

How can we fix that the /is top and /is level is loaded and it doesn't calculated over and over again when players perform the commands? This causes a high cpu usage when players use these commands and we want to prevent that.

Kind regards,
det483

**Comment by csorrows** [comment]
Wait, so at idle uSkyblock is using 20-60% cpu?

**Comment by dutchy1001** [comment]
Can you give us a timings report?
Type "/timings on" (as Op) and let it run for 15 to 30 minutes, then type "/timings paste" and post that link here.
This will help to see were it goes wrong or were to look at.

**Comment by rlf** [comment]
I can chime in with what SHOULD happen.

1. The `/is top` will ONLY re-calculate the top-ten if one or more of these:
  1. The player has permission `usb.admin.topten`
  2. The player is OPed
  3. The issuer is console
  4. The top-ten wasn't generated within `options.island.topTenTimeout` minutes

I.e. for "normal players", you can configure how often the top ten is recalculated, but if you issue the command (as OP/admin) you will get a freshly calculated top 10.

Top-list calculation is by nature a time-consuming process, which is why we do not recommend calling it too often. Unfortunately, a lot of servers setup "scoreboards", that call the top-ten as console at a fixed interval. If this interval is "too small", it is bound to show up on the performance timings reports.

As Dutchy pointed out, try posting the actual timings reports - as it tells us a bit about the frequency, and timings of the calculations.

**Comment by csorrows** [comment]
Thanks for the detailed process for island level calculation @rlf , I did not realize it had changed. :)

**Comment by det483** [comment]
Hello,

I forgot this report so it took a long time to react, but here is the timing report;
http://timings.aikar.co/?url=14354483

And yes we use a scoreboard, the featherboard plugin and we also use leaderheads. Is this causing the high cpu usage? If so how can we fix that. Should we disable these plugins or what should I do?

Kind Regards,
det483

**Comment by rlf** [comment]
The timings shows, that it's not the scoreboards, and not the top-10 calculation, but only the fckdup way we currently handle UUID (known issue, see #540 and #231), it's a priority to handle this, unfortunately, it requires a rewrite of more or less the whole data-model used in uSkyBlock - so it hasn't been done yet.

Also, the timings shows that the server is not lagging, but only occasional (when players join or leave).
uSkyBlock is not the only one struggling with join/leave - but we can do better.

**Comment by dutchy1001** [comment]
there have been no more complains about this issue, I guess later version resolved this.

Closed for now, if reoccurring you can always re-open or make a new issue.
