### ISSUE TITLE
USkyblock

### ISSUE THREAD

**Issue by MajesticGoat63** [rlf/uSkyBlock#656]
On my server players can't place blocks break blocks or access the chest plz help me.

**Comment by dutchy1001** [comment]
Depending on what you use this can be many thing but not a uSkyblock issue. 
Do you use Groupmanager, Pex or any other permission plugin?
If you you use **Pex** make sure players have ```modifyworld.*```
If you use **Essentials** make sure you give players ```essentials.build```
If you use **Groupmanager** make sure you have set ```build``` to ```true```

Yet again this is not a uSkyblock issue so I can close this.
If you need more help let me know (no need to open new issue, continue here if needed).

**Comment by MajesticGoat63** [comment]
Thanks, but what if I use both essentials and pex?

**Comment by csorrows** [comment]
Try removing EssentialsAntiBuild.

**Comment by MajesticGoat63** [comment]
I don't have essentialsantibuild I have worldguard though.

**Comment by dutchy1001** [comment]
Then put the essential permission nodes in pex

**Comment by MajesticGoat63** [comment]
I have. I've put modifyworld.* and essentials.build but it doesn't work.

**Comment by SgtLegoTown** [comment]
If you are OP you can break blocks because if I read back you are talking about "players".  If players can't break and you can its a permissions issue or region settings maybe overpowering spawn protect.  It can be many things the best way is to look at every single plugin and what permissions they need.  If you really don't get it fixed i' am willing to help. This isn't a discussion that should be here in the uskyblock plugin as it is a permission issue and not a uSkyblock issue.

**Comment by MajesticGoat63** [comment]
Okay thanks.

**Comment by csorrows** [comment]
I **LUVZ** your title change @rlf =)

**Comment by rlf** [comment]
Well it seemed more correct than the previous one :)

**Comment by SgtLegoTown** [comment]
at least I dint break it this time ...
