### ISSUE TITLE
[Suggestion] Previous challenge requirement for challenges

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#676]
I think the ability to specify a challenge being completed as a requirement to complete another specific challenge could be helpful. Thinking about how I could improve my challenges and make them unique, one idea I had was to create "unlock" challenges. For example, a challenge that requires a certain number of a certain crop fully grown on your island could unlock another challenge where you can turn in X amount of that crop, essentially requiring the player to at least grow some of the crop rather than buying it all from a server shop. Unfortunately, I couldn't implement the idea since setting a challenge requirement only appears to be possible for challenge _categories_, rather than specific challenges.

**Comment by rlf** [comment]
Yes, Ranks support requirements, challenges do not.
Not sure how hard this will be, but we can take a look.

**Comment by rlf** [comment]
Considering doing this, but I have one very important question.
Should the challenge WIN over the rank? I.e. if the rank is still locked, but the challenge is enabled, should it be? Or should it be an additional requirement for unlocking the challenge?

I vote for the latter.
Since you can always have a rank active, and then just have all the challenges be individual.
+ it would enable you to activate the rank at a level (requires challenge adept-builder), and then have progressions depending on previous challenges.

**Comment by BlackBeltPanda** [comment]
I would agree with your vote, the latter is how I would expect it to function. =)

**Comment by BlackBeltPanda** [comment]
Working great. =D
