### ISSUE TITLE
Mob limiter not limiting Blazes

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#696]
Had a report of my server's TPS dropping to 3, so I logged in to find a player's island had 1,700 blazes.  They had a blaze grinder setup using 3 monster spawners. Their monster limit is 140.

USB Version output: http://pastebin.com/raw/9t4h2gC9

**Comment by rlf** [comment]
Probably related to #686

**Comment by rlf** [comment]
In #686 we adjusted the spawnlimits to allow for admins to spawn monsters regardless of these limits.

To accomodate some other requests, that meant we allowed "spawners" (as the blocks) to circumvent the spawn-limits - as those was deemed in that particular setup to be "admin placed".

I see that some servers will allow players to purchase spawners, so that decision need to be reverted.

**Comment by BlackBeltPanda** [comment]
Yeah, selling spawners is pretty popular. I've even created a custom GUI that players can access by right-clicking a spawner to allow them to choose, for a fee, what mob will spawn.

Thanks for reverting =)

**Comment by BlackBeltPanda** [comment]
Haven't had any issues; seems to be working. =)
