### ISSUE TITLE
Server lag on "/is restart" resulting in server time out

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#709]
Immediately after starting up my server it begins to lag badly to the point it crashes.
Looking at the timings, it seems to be a combination of the furniture plugin I'm using and uSkyBlock.
Timings: http://timings.aikar.co/v2/?id=978a411488ab40e2b1c2dc21ca904723&section=lag#21_

uSkyBlock also took an unusually long time to startup after the server had finished loading. Normally it's loaded before the server's done loading.:
```
[15:43:49] [Server thread/INFO]: Done (23.792s)! For help, type "help" or "?"
[15:44:24] [Server thread/INFO]: [uSkyBlock] uSkyBlock hooked into Vault Economy
[15:44:24] [Server thread/INFO]: [uSkyBlock] uSkyBlock hooked into Vault Permissions
[15:44:25] [Server thread/INFO]: [uSkyBlock] uSkyBlock hooked into MVdWPlaceholderAPI
```
Version info: http://pastebin.com/raw/7yk9wAw6

Update:
It seems the lag happens after a player runs "/is restart". Each time my server restarted, at least one player would immediately run "/is restart". Not sure if they were doing it maliciously, realizing it lagged the server out, or if they were legitimately trying to restart. Either way, the command completely locked up my server until it timed out. For the time being, I've disabled the ability for players to restart their islands on my server and no more lag.

**Comment by rlf** [comment]
Thanks for (yet-another) precise and well-document issue report.

I need some more info (which we should probably put in `/usb version` at some point).
a) How big are your islands? (`protectionRange` and `distance`)
b) Is nether enabled? (`config.yml:nether.enabled`)
c) Is the AWE enabled (`config.yml:asyncworldedit.enabled`)

The thing is, we've done a lot to keep the lag from `/is restart` down, but some operations we are not able to do much about.

That includes the clearing and pasting using WE.

To optimize the clearing, we recommend using protectionRanges that align to chunk-borders (divisible by 32) - that way, WE won't be used for clearing - only the world-native-regen.

For some of the WE operations, using AWE helps - but we struggle to keep our plugin "compatible" with AWE - since it has been known to break backwards-compatibility in the past.

**Comment by BlackBeltPanda** [comment]
protectionRange: 304
distance: 500
Nether Disabled
AWE Enabled

I'd definitely like to change my protectionRange value to something chunk-aligned so I can enable the nether but haven't had the heart to reset the skyblock world, yet, given all the players and islands we have right now. My staff are currently hard at work on a new set of unique challenges so I'll probably reset the server once those are done; that way I can at least use the "everyone gets a fair start" excuse. XD

I wasn't aware that USB utilized native chunk regen for island resets in chunk-aligned cases. That's definitely another good reason to keep things chunk-aligned. Just a thought: If the difference between the protectionRange and distance values is greater than 32, couldn't the island chunks be regenerated without WE by rounding the island borders to the nearest chunk?

**Comment by rlf** [comment]
Yes, we have considered that performance optimization.

And we will most likely implement it eventually - but the logic surrounding the "chunk-operations-on-island-size" has been causing quite much head-ache in the past.

Since the nether sort of required us to insist on chunk-alignment, we haven't prioritized it.

Though, in your setup, it would most likely make sense.
We could even allow nether for non-chunk aligned worlds then - but only if distance is large enough to guarantee any chunk-alignment between protectionRange an distance won't overlap neighbouring islands.

**Comment by BlackBeltPanda** [comment]
Would be cool but no rush; I do plan to reset my server once my staff get the new challenges setup.
If I can manage some free time some day soon I'll help knock some of the issues off the list for you. =)

**Comment by BlackBeltPanda** [comment]
Awesome; working great =D
Island clearing is much faster now and no sign of any lag. =)

**Comment by rlf** [comment]
Glad to hear. Closing.
