### ISSUE TITLE
No folder

### ISSUE THREAD

**Issue by Melowelei** [rlf/uSkyBlock#741]
Hi,

I don't have in my GroupManager folder the folder " uSkyBlock " for put some rank at my players, why ?

cordially

**Comment by SgtLegoTown** [comment]
you did read the group manger wiki ? 
http://wiki.ess3.net/wiki/Group_Manager specially the Initial Install part)

and if group manger did nor make the directory's after setting the config ,yml my logic says generate a new config and Group manger dir OR manually add,.
I have a feeling uskyblock cant make dirs. for group manger since its a other plugin with its own config

**Comment by dutchy1001** [comment]
As far I know Groupmanager will not make the uSkyblock folder, 
1. because that folder should be in your plugins folder
2. if there is a folder it should be called "skyworld" named after the "world" name you use for uSkyblock.

You need to copy the default world and rename this "skyworld", from there you work your permissions out.

You need to read up about how GroupManager works, the link from SgtlegoTown is one that can help but there are some more in the list [here](http://wiki.ess3.net/wiki/Tutorials).

This is not a uSkyblock issue but a general knowledge of how plugins work, therefore this will be closed
