### ISSUE TITLE
[Feature Request for API] Customization of certain aspects.

### ISSUE THREAD

**Issue by Azoraqua** [rlf/uSkyBlock#768]
I would like to see if it's a possibility to add direct customization though the API. 
Such as changing biome, creating schematics, editting schematics, changing chestloot, and definitely more events (They speak for theirself when they should be fired):

- IslandCreateEvent
- IslandDeleteEvent
- IslandRestartEvent
- ChallengeCompleteEvent
- PerkUnlockEvent
- SettingChangeEvent
- IslandInviteEvent
- IslandChangeEvent (Thanks to @jesseke55 )

**Comment by jesseke55** [comment]
Maybe also a IslandChangeEvent?

**Comment by rlf** [comment]
Questions (apparently, they don't speak for them selves) :)

When would PerkUnlockEvent be fired?
What do you think SettingChangeEvent should be? (per island?)
and what exactly are you thinking should merit an IslandChangeEvent (are we talking blocks, invites, trustees, warps, homes, level?)

**Comment by Azoraqua** [comment]
@rlf I am not sure, but I saw in the 'core' something about Perks so I thought it would be a possibility to have a PerkUnlockEvent. 

And the SettingChangeEvent is for Settings about the island specific, and possibily global settings (Like for example dying when falling off, turning the 'lava losing protection' off and such).

Also the IslandChangeEvent specifically about the Island itself, the possibily changed blocks, invites, trustees, warps, homes, level :)

**Comment by rlf** [comment]
It won't be "too hard" to introduce those events, but, if you want any of them to be `Cancellable`, most of the logic-flow would need to be re-factored.

**Comment by Azoraqua** [comment]
@rlf I don't think any of them really needs to be Cancellable. I would rather see an Enum with for example the Result: DENY, ACCEPT (For IslandInviteEvent) and further not really something :)

Maybe a menu where Global/Island settings can be changed?

**Comment by Victhetiger** [comment]
Since this was already created, it might not have anything to do with the API but a MVDW placeholder called "island_level_rounded" would be quite nice because the current level on my scoreboard is like infinite.

**Comment by rlf** [comment]
if you use OUR placeholders, you can use `usb_island_level` which is rounded to 2 decimals.
Not sure whether they actually work, but worth a try :D

**Comment by Victhetiger** [comment]
That's what I'm using, it works in the first 20-70 levels but when they get to 100 or so it's like 100.1202019129199121992 on the scoreboard, it doesn't end.

**Comment by Azoraqua** [comment]
@rlf Maybe it's better to simplify the `island_level` to Integer (Example Math.round())?

**Comment by rlf** [comment]
`island_level` is not something uSkyBlock provide - it's something you get from another plugin (called MVdWPlaceholders).

**Comment by Azoraqua** [comment]
@rlf As of Issue #773 could you possibly add a `getHomeLocation()` method?
Also back to the main subject of this "Issue", I'll take a look into the API about the Events.

**Comment by rlf** [comment]
As stated above, no.
But I might be able to introduce a getPlayerInfo() method, that would return an object that has that info.
Not 100% sure though.

**Comment by Azoraqua** [comment]
@rlf That would be nice. Either way I am glad you want to take a look at it :)

**Comment by Azoraqua** [comment]
@rlf Could you possibly also add one or more methods to create a island, and join a party (For example `createIsland()` and `joinParty()`)?

**Comment by Victhetiger** [comment]
Again, out of context. There's already a way to implement my suggestion to the Island level. If you use MVDW's plugin you can do <round>{uskyblock_island_level}</round> or something like that. Sorry for getting out of context.

**Comment by jesseke55** [comment]
@Victhetiger This isnt going about island levels.... @Azoraqua is talking about something else.

**Comment by rlf** [comment]
This issue is about API "customization" of "certain aspects".

I've added some basic events, where I think they are appropriate.
I do not like (or intend to add) API methods for doing stuff like `joinIsland` or `createIsland` - since they are both highly complex, and involves the user, something I do not feel confident having initiated from a 3rd-party plugin.

If you want to achieve such things, you can ofc. still dispatch the commands to the plugin - so the plugin is still in complete control of the process.

Reg. the placeholders, we already support a wide range of placeholders, both as an internal-placeholder support, and as a plugin to MVdWPlaceholderAPI.

We do (however) NOT SUPPORT the placeholders maintained by thirdparty plugins (as the ones provided directly in MVdWPlaceholders).

Our placeholders start with `usb_`, the ones starting with `uskyblock_` is provided with MVdWPlaceholders (see https://www.spigotmc.org/wiki/mvdw-placeholders/#uskyblock-2-4-or-higher).

For a list of our placeholders, see https://github.com/rlf/uSkyBlock/blob/master/uSkyBlock-Core/src/main/java/us/talabrek/ultimateskyblock/handler/placeholder/PlaceholderReplacerImpl.java
Note: The placeholder feature is still highly experimental.

**Comment by Azoraqua** [comment]
Okay, Alright. Let's close this Issue because it's getting inrelevant.

**Comment by Victhetiger** [comment]
@jesseke55 "Again, out of context" Answering my own issue I posted earlier in this thread.

**Comment by Azoraqua** [comment]
@Victhetiger Please make your own Issue for this.

**Comment by Victhetiger** [comment]
Sorry for disturbing your thread, but it is no need anymore as it is fixed.
