### ISSUE TITLE
[Suggestion] "/it" toggle listener priority

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#831]
The listener priority for the AsyncChatEvent being set to "HIGHEST" will probably interfere with most chat format plugins. I had to set my chat format plugin to listen at priority "MONITOR" in order for "/it" to properly cancel the chat event. I would recommend setting the priority to "NORMAL" or "HIGH".

**Comment by rlf** [comment]
As far as I understand the priority, the HIGHEST will be the LAST one allowed to cancel any event (since MONITOR strictly speaking isn't allowed to do that).

I used HIGHEST to allow other plugins to do placeholders etc. before I cancelled the event.

**Comment by BlackBeltPanda** [comment]
That's what I mean. For example:
Chat Formatter on HIGH will send the message in public chat since it hasn't been cancelled, yet.
Meaning if you toggle into "/it" and type a message, it gets sent to both public chat and island chat unless the chat formatter is set to MONITOR.

**Comment by rlf** [comment]
No formatter on the event-chain should "sent messages" to chat, the whole idea with the event chain is, that it's the MONITOR that actually takes-action, depending on what the listeners has done to the event.

If I were to do stuff earlier, it wouldn't be a "nice design", but I see what your concern is.

Do you have a specific incompatibility I could look into?

Since, if I were to follow the logic you describe, I should simply do my thing on the LOWEST priority.

**Comment by BlackBeltPanda** [comment]
Yeah, I know what you mean. Chat events tend to get a bit messy when you have formatters and filters all listening and acting on them.
In my case, [ChatControl](https://www.spigotmc.org/resources/chatcontrol.271/) is the main incompatibility; I have to set its "Formatter" listener priority to "MONITOR" in the config, which then breaks my punishment plugin's mute command.

**Comment by BlackBeltPanda** [comment]
Working great now =D
