### ISSUE TITLE
Distance is not changing

### ISSUE THREAD

**Issue by UnioDex** [rlf/uSkyBlock#897]
Hi i changed my distance and protection-range variables as 110. But players can only build 105 blocks. And their block levels are not counting. 

http://prntscr.com/codbca

**Comment by dutchy1001** [comment]
you can only change the **distance** and **protectionRange** value's when there are no islands created yet. 
Reset the world and see if it still happens (remember to reset the "worldGuard" files aswell).

**Comment by UnioDex** [comment]
I didn't changed my distance already. I created world with 110. But when i update plugin from 2.0 to 2.7.3 this problem has been started.

**Comment by rlf** [comment]
The "players can only build 105 blocks" indicates, that the WorldGuard regions where created with 105 as distance.

The WG regions should be automatically updated when the players log-on - if not, you can force it using the `/usb wg` command.

Please also provide the output of `/usb version` - which tells us a lot of important information, incl. the actual distances in play.

**Comment by dutchy1001** [comment]
The value's 110 and 105 were default when you set up the server a while back. When updating to 2.7.3 those value's were changed, for new servers, due to the adding of our Nether feature, old servers (but updated to 2.5.3 and upwards) would keep the 110 and 105 value's.

I'm not sure that the format has changed in between version v2.0 to v2.5.3 for the WorldGuard regions and that could be the cause it didn't update. As rlf already said to use the _/usb wg_ command should fix this.

On an other note I would **not recommend** to change those value's after an island has been created in the skyworld. Those value's should only be set when there are no island present yet as it can cause many many problems.

**Comment by UnioDex** [comment]
I didn't change any value. Also with 2.0 i weren't use WorldGuard protection. I had my own guard plugin. All regions are created from zero. But it is not about only WorldGuard. Also placed block levels are not counting.

**Comment by UnioDex** [comment]
For example:

I deleted an island but some of them blocks are stayed:
http://imgur.com/GnraHQu

**Comment by dutchy1001** [comment]
> I had my own guard plugin.
This might be something that can cause issue's, as far I know uSkyblock v2.0 already used the WorldGuard protection. If you did change this then that is something we can't take into consideration.

Seems to me that the jump from v2.0 to v2.7.3 is to big and to stop all the issue's a full server reset might be the best and easiest solution then.

**Comment by UnioDex** [comment]
Yes but it is impossible players wont accept that :/

**Comment by rlf** [comment]
If you jump from 2.0 to 2.7, you need to at least run some of the importers.

I think one of the required ones are `/usb import wolfwork` - depending on the actual 2.0 version you were previously using.

**Comment by UnioDex** [comment]
I made all imports. Wolfwork import print:

`>usb import wolfwork
[17:34:31 INFO]: [uSkyBlock] Importing 2 files
[17:34:31 WARN]: [uSkyBlock] Could not import file plugins/uSkyBlock/orphanedIslands.bin
[17:34:31 INFO]: Progress: 50% (1/2 - success:0, failed:1, skipped:0) ~ 0sn
[17:34:31 WARN]: [uSkyBlock] Could not import file plugins/uSkyBlock/players/errors
[17:34:31 INFO]: Progress: 100% (2/2 - success:0, failed:2, skipped:0) ~ 0sn
[17:34:31 INFO]: Converted 0/2 files in 0sn
`

**Comment by UnioDex** [comment]
What do you recommend? May i update the plugin version by version? (2.0, 2.1, 2.2, etc.)

**Comment by dutchy1001** [comment]
> Yes but it is impossible players wont accept that :/

So why don't you ask them that the before having all these issue's?
For what they get back in new features should be enough to convince them to restart.

Few of the new features:
- Better protection per island
- New Nether feature
- Better party for playing with friends
- Customised island (can be set per rank)
- Different limits (for mob/animal farms per island/rank)
- Private party or island chat

To do time consuming bug fixes that are for 99% caused by a version that is so obsolete is a waste of time IMHO (I only know 1 person that uses this 😉). I know it's easy to say for me as I don't do the coding.

**Comment by dutchy1001** [comment]
Am I understanding this right that the uSkyblock v2.0.0 is not an original but altered or fork?

Original v2 error mesage:
```
[11:17:04 ERROR]: Error occurred while disabling uSkyBlock v2.0.0 (Is it up to date?)
```
Your error message:
```
[17:27:15 WARN]: [USB2] Task #1142 for USB2 v2.0-SNAPSHOT generated an exception
```
If your not using the original version from were we took over from Talabrek then there is nothing much we can do, errors can be caused by code we cant access.

Yet again then your best solution is to reset the skyworld or updating to a newer version will be impossible due to the "altered" code we cant update.

**Comment by UnioDex** [comment]
No, i am using Talabrek's uSkyBlock. USB2 is my extra plugin for uSkyBlock server. I will make a new Skyblock server but i also want support my old server for this reason i am searching a solution.

**Comment by dutchy1001** [comment]
If you have a bungee setup you can run both, aslong you have each skyblock on a separate server. That way you can keep all players happy. They can then decide to either go to their old island or start fresh with an up to date version.

**Comment by UnioDex** [comment]
Yes solution is this for me. If another person lives that problem he can open another ticket. Thanks for your helps.
