### ISSUE TITLE
As I can put it in Spanish?

### ISSUE THREAD

**Issue by SpeedMatias** [rlf/uSkyBlock#918]
Hello I just call matias and the truth that the plugins is very good but I am Spanish and would like to put the plugins in Spanish as I can put it? change all that is in Spanish could help me?

**Comment by Lmmb74** [comment]
English:
Try avoiding the use of google translate xDDD. You just have to change the value language in config.yml to es (which is used for Español) instead of en (which is used for English) :P Hope it helped you :D

Spanish
Deberías evitar usar google translate xDDD. Solo debes ir al archivo config.yml y modificar el valor language de en (valor utilizado para English [Inglés]) a es (valor utilizado para Español) :P Espero haberte ayudado :D

**Comment by SpeedMatias** [comment]
lo que pasa que no se ingles soy español, ya le puse lenguage: es y igual sigue en ingles..!

**Comment by Lmmb74** [comment]
Que raro...

**Comment by dutchy1001** [comment]
I'm not sure if the Spanish translation is up to date but you can set it with the command **/usb lang es**.
If not, you can translate it to your own liking. Have a read on this page [here](https://dev.bukkit.org/bukkit-plugins/uskyblock/pages/localization/) to see how you can update or create your own language file.

Ps.
Thank you for the compliment for our plugin 😃

**Comment by dutchy1001** [comment]
due to no further input I close this.
