### ISSUE TITLE
"stopTiming called async" and "Failed to save chunk"

### ISSUE THREAD

**Issue by BlackBeltPanda** [rlf/uSkyBlock#933]
_Please paste the output from `/usb version` below_
```
Name: uSkyBlock
Version: 2.7.3-alpha5
Description: Ultimate SkyBlock v2.7.3-alpha5-576cd3-436
Language: en (en)
State: d=500, r=152, i=3,496, p=12,456, n=false, awe=true
Server: Paper git-Paper-908 (MC: 1.10.2)
State: online=true, bungee=true
------------------------------
Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1.3;7a097ca (ENABLED)
WorldGuard 6.1.2;e38d98d (ENABLED)
FastAsyncWorldEdit 16.11.17-e16bcae-372-9.11.4 (ENABLED)
Multiverse-Core 2.5-b719 (ENABLED)
Multiverse-NetherPortals 2.5-b710 (ENABLED)
------------------------------
```

_What steps will reproduce the problem?_
Each time my server starts, I see errors pertaining to "stopTiming called async" and "Failed to save chunk". The stack traces both reference uSkyBlock and FeatherBoard. I'm not sure which is relevant in this case.

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: http://pastebin.com/raw/iKQJnzQs

Edit: Ah, nvm, didn't realize I was a few versions behind. Updating seems to have solved the issue. =)

**Comment by BlackBeltPanda** [comment]
Ah, nvm, didn't realize I was a few versions behind. Updating seems to have solved the issue. =)

**Comment by BlackBeltPanda** [comment]
Spoke too soon. Another restart later and it's happening again.
```
Name: uSkyBlock
Version: 2.7.3-alpha9
Description: Ultimate SkyBlock v2.7.3-alpha9-0d8854-444
Language: en (en)
State: d=500, r=152, i=3,496, p=12,456, n=false, awe=true
Server: Paper git-Paper-908 (MC: 1.10.2)
State: online=true, bungee=true
------------------------------
Vault 1.5.6-b49 (ENABLED)
WorldEdit 6.1.3;7a097ca (ENABLED)
WorldGuard 6.1.2;e38d98d (ENABLED)
FastAsyncWorldEdit 16.11.17-e16bcae-372-9.11.4 (ENABLED)
Multiverse-Core 2.5-b719 (ENABLED)
Multiverse-NetherPortals 2.5-b710 (ENABLED)
------------------------------
```

**Comment by rlf** [comment]
Is it an existing world-setup or a clean world?
Because, the issue arises because we get called by featherboard before the worlds has fully loaded (at least that would be my notion of it).

uSkyBlock will wait (on purpose) for a fixed amount of time, before accessing worlds internally, since we are both a plugin, and a world-generator - we get loaded before world-generation. Featherboard should not access us, before worlds has been loaded - but they do.

So, create an issue at Featherboard - they are not even using our API - which means, we have no way of controlling what they do from our end.

**Comment by BlackBeltPanda** [comment]
Ah, ok, thank you. Wasn't sure which plugin was causing the issue. I reported the issue to the FeatherBoard dev. =)

**Comment by BlackBeltPanda** [comment]
Quoting MVdW:
"This is a check that should be added into uSkyBlock , because as an external plugin hooking into the API I have no information about where an island is located"

**Comment by rlf** [comment]
The point is, he isn't using the API. Since his code is closed-source, I have no way of seeing how he is accessing our plugin.

The only way we can control the way he accesses us, is to split our plugin into two - one part being the world-generator (loading before worlds) and another part being the actual plugin (after world-generation).

We cannot do that atm.

Protecting every piece of code in our plugin against "premature access" is not feasible, we could how-ever throw a different exception when being accessed before the worlds load - but I cannot understand why featherboard needs to load during startup - it should be loaded later in the initialization phase (i.e. after the worlds has been populated).

**Comment by BlackBeltPanda** [comment]
Going to close this since it's an issue on Featherboard's end, though the dev refuses to fix it. I'll just setup a console/log filter for now so the errors aren't written. =)
