### ISSUE TITLE
Give or take away permissions with a command.

### ISSUE THREAD

**Issue by MacMasterMac** [rlf/uSkyBlock#963]
WE: 6.1.3
WG: 6.1.2
MV-C: 2.5
MV-P 2.5
USB: 2.7.3-alpha5
Server: CraftBukkit 1.8.8

Suggestion: Everything in the /is GUI also has a command, exept the island member's permissions :/
» /is » Island group » Player name » and then you see permissions (http://prntscr.com/dvkcxn)

I would like to have a command such as /is member {island member} {permission} <true/false>
When player is not part of island it says something like: "You can only give players permissions that are in your island party"

The permissions from the gui are:
- Can change biome
- Can lock island
- Can set island warp
- Can toggle island warp
- Can invite players
- Can kick players

I've also noticed that when I try to change the gui name "Hello <Permissions>" to "Hello's permissions" it kind of glitches. When I click an icon it adds another "s" behind my name and the icons don't work. 
Looks like this:  "Hello'ssssssss permissions" I edited it with po.

Let's hope :D

**Comment by rlf** [comment]
* Don't bunch multiple issues in one.
* Use the output of `/usb version` as we ask for - since it gives us the info we need.
* Use POEdit for making translations (hint: you need to use double `''` instead of one).
* We are aware of that part that is missing a command line, and that should definitely be a feature (but hasn't been prioritized for ages).

**Comment by OMGYES** [comment]
- Bunch of issues? I only said one thing! (At the bottom)
- I did put my usb output??? (On the top)
- I just said I use po (means poedit)
- Well that's good to hear I hope to hear something soon...
