### ISSUE TITLE
Server lag on /is level

### ISSUE THREAD

**Issue by mikroskeem** [rlf/uSkyBlock#981]
_Please paste the output from `/usb version` below_
```
 Name: uSkyBlock
 Version: 2.7.2
 Description: Ultimate SkyBlock v2.7.2-45f756-430
 Language: en (en)
   State: d=512, r=256, i=3, p=3, n=true, awe=true
 Server: Paper git-Paper-1056 (MC: 1.11.2)
   State: online=false, bungee=false
 ------------------------------
 Vault 1.6.7 (ENABLED)
 WorldEdit 6.1.7-SNAPSHOT;3677-000c238 (ENABLED)
 WorldGuard 6.2.1-SNAPSHOT;1703-85693b9 (ENABLED)
 FastAsyncWorldEdit 17.02.13-4caadb8-517-10.8.11 (ENABLED)
 ------------------------------
```

_What steps will reproduce the problem?_
1. Set up server using uSkyBlock (main worlds are for skyblock, worlds are generated using CleanroomGenerator, a'la `worldName: world` and `generator: CleanroomGenerator:.`)
2. Play as usual
3. Do `/is level`

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: (nothing interesting in log)

(Not following the template will result in closing the issue.)

Timings could help though: https://timings.aikar.co/?id=c7c84286df48420c969f86f34dc070fc

Edit: Vault is custom. But that shouldn't cause any problems (API hasn't been changed).  
Edit 2: Maybe it is related to `options.island.disance` set to 512?

**Comment by mikroskeem** [comment]
Any updates on this? This issue is still open and problem haven't gone anywhere.

**Comment by dutchy1001** [comment]
The plugin will generate the worlds as it will set a few parameters, this might not be done while using CleanroomGenerator, might be a cause.
If you have set it as main world in the server.properties then that is not good either. let the "default" world be world and let uSkyblock generate the needed worlds.

**Comment by mikroskeem** [comment]
> If you have set it as main world in the server.properties then that is not good either. Let the "default" world be world and let uSkyblock generate the needed worlds.

That doesn't seem to cause a problem, world is a world.

Seems like lowering `options.island.disance` resolved my issue. But that isn't really a solution for this imo.

**Comment by dutchy1001** [comment]
I just notest that you dont have all the depended plugins in your server, multiverse is missing.

**Comment by mikroskeem** [comment]
It doesn't seem to be fully required either, plugin doesn't die if it isn't installed.

I must note `us.talabrek.ultimateskyblock.island.task.ChunkSnapShotTask` class causes lag.

**Comment by dutchy1001** [comment]
It does

**Comment by mikroskeem** [comment]
Tested this again with Multiverse-Core (after #988 issue), nothing changed.

**Comment by rlf** [comment]
This "issue" keeps coming back, and it's not much we can do about it.

As mentioned else-where, in the countless other issues, we calculate the island score quite efficiently, but since we do it, by scanning all the blocks within the island, it's a lengthy and performance heavy task.

The task your performance log shows takes some time, is the task that asks Bukkit for chunk-snapshots.
If you look into the numbers, it's actually performing quite well, most of the time, but yes, it takes time.

It averages out at 16ms per task, which is acceptable (a tick is max 50ms), the reason it shows as red, is that it sometimes takes longer time (most likely when the server is saving or unloading chunks - given the other numbers).

Usually, we only calculate the numbers periodically (i.e. we cache the results), but as OP you will get the calculation run every time.

If you have a more efficient way to do the chunk-snapshotting, by all means, let me know.

**Comment by dutchy1001** [comment]
That's because the world has been created with CleanroomGenerator and not with our buildin generator. You might need to redo the whole world.

**Comment by rlf** [comment]
well, cleanroomgenerator should be more or less the same as our generator.

But having islands of size 256 is putting pressure on it. We had some testing done once with 1024, where it still works, but the performance will be impacted, esp. on `/is info`, `/is level` and the top-ten generation (as OP).
