### ISSUE TITLE
island top bug?

### ISSUE THREAD

**Issue by AmaranthineEon** [rlf/uSkyBlock#986]
_Please paste the output from `/usb version` below_
```
26.02 17:33:48 [Server] INFO Name: uSkyBlock
26.02 17:33:48 [Server] INFO Version: 2.7.2
26.02 17:33:48 [Server] INFO Description: Ultimate SkyBlock v2.7.2-45f756-430
26.02 17:33:48 [Server] INFO Language: en (en)
26.02 17:33:48 [Server] INFO State: d=256, r=128, i=47, p=34, n=false, awe=false
26.02 17:33:48 [Server] INFO Server: CraftBukkit git-Spigot-6de2fbc-16b5116 (MC: 1.11.2)
26.02 17:33:48 [Server] INFO State: online=true, bungee=false
26.02 17:33:48 [Server] INFO ------------------------------
26.02 17:33:48 [Server] INFO Vault 1.5.6-b49 (ENABLED)
26.02 17:33:48 [Server] INFO WorldEdit 6.1.5;4651611 (ENABLED)
26.02 17:33:48 [Server] INFO WorldGuard 6.1.3-SNAPSHOT;c904242 (ENABLED)
26.02 17:33:48 [Server] INFO AsyncWorldEdit 2.3.2 (ENABLED)
26.02 17:33:48 [Server] INFO Multiverse-Core 2.5-b719 (ENABLED)
26.02 17:33:48 [Server] INFO Multiverse-Portals 2.5.0-SNAPSHOT-b748 (ENABLED)
26.02 17:33:48 [Server] INFO ------------------------------
```

_What steps will reproduce the problem?_
1. Not exactly sure what I did, but I used the purge command. It suppose to delete the island also right, but the island were still there? If i typed /usb goto, it would say they don't have an island, however the island top still has their name on it. Then when they remade their island again, it just added their username under their first one but the island level never got deleted. I tried registering their username to the old island but it would again, make a third name on the island top.
2. http://prntscr.com/edqwr4
3.

_If you have any log-files, please paste them to [pastebin.com](http://pastebin.com)_
* server-log: link-to-pastebin

(Not following the template will result in closing the issue.)

**Comment by dutchy1001** [comment]
The purge command does not delete the island, but should remove all "data" from the players file, basically a reset as that the players doesn't have an island.
The reason the purge does not delete the island itself is to prevent lag. Because you can purge many islands at the same time the server has to work to much which then causes the lag.
The island(s) that has been purged will only be replace when a new island is created by a player.
The command **_/usb island delete [playername]_** will delete not only the data from the file but also delete the island.
As you did the command **_/usb goto [playername]_** you saw it didnt work as the data was **purged**.
The island top has a default interfall to refresh but by default set to 0 (zero) meaning disabled.
If you do the command **_/usb topten_** it should regenerate the top ten again and correct itself, if not let me know.

**Comment by AmaranthineEon** [comment]
Ah yes, thank you for clearing up some of the commands for me. However, doing /usb topten still gives me the same list. It hasn't changed. The default is set to 1 so it has not been disabled either. 
I got that player to come on and to /is restart but it just made another island. Now their on the list 3 times.

**Comment by AmaranthineEon** [comment]
We figured out a way to get rid of it by going into the files.

**Comment by rlf** [comment]
I've seen this before - but have totally forgotten about it.
It seems you can be listed on the top-list multiple times, under different islands, I think we need to investigate further.

**Comment by rlf** [comment]
Cannot reproduce it on latest version.
Did the following
```
R4zorax                       MyFuglsang
/is invite MyFuglsang             
                              /is accept
                              Disconnect
/is kick MyFuglsang
```
And everything looks dandy, party-size is 1
